import { PokedexEntry, PokemonType, Stats, Move } from '@/types/game';

// Common moves used throughout the game
export const MOVES: { [key: string]: Move } = {
  tackle: { name: 'Tackle', type: 'Normal', power: 40, accuracy: 100, pp: 35, maxPp: 35 },
  scratch: { name: 'Scratch', type: 'Normal', power: 40, accuracy: 100, pp: 35, maxPp: 35 },
  ember: { name: 'Ember', type: 'Fire', power: 40, accuracy: 100, pp: 25, maxPp: 25 },
  waterGun: { name: 'Water Gun', type: 'Water', power: 40, accuracy: 100, pp: 25, maxPp: 25 },
  vineWhip: { name: 'Vine Whip', type: 'Grass', power: 45, accuracy: 100, pp: 25, maxPp: 25 },
  thunderShock: { name: 'Thunder Shock', type: 'Electric', power: 40, accuracy: 100, pp: 30, maxPp: 30 },
  bite: { name: 'Bite', type: 'Dark', power: 60, accuracy: 100, pp: 25, maxPp: 25 },
  flamethrower: { name: 'Flamethrower', type: 'Fire', power: 90, accuracy: 100, pp: 15, maxPp: 15 },
  hydroPump: { name: 'Hydro Pump', type: 'Water', power: 110, accuracy: 80, pp: 5, maxPp: 5 },
  solarBeam: { name: 'Solar Beam', type: 'Grass', power: 120, accuracy: 100, pp: 10, maxPp: 10 },
  thunderbolt: { name: 'Thunderbolt', type: 'Electric', power: 90, accuracy: 100, pp: 15, maxPp: 15 },
  psychic: { name: 'Psychic', type: 'Psychic', power: 90, accuracy: 100, pp: 10, maxPp: 10 },
  earthquake: { name: 'Earthquake', type: 'Ground', power: 100, accuracy: 100, pp: 10, maxPp: 10 },
  iceBeam: { name: 'Ice Beam', type: 'Ice', power: 90, accuracy: 100, pp: 10, maxPp: 10 },
  surf: { name: 'Surf', type: 'Water', power: 90, accuracy: 100, pp: 15, maxPp: 15 },
  hyperBeam: { name: 'Hyper Beam', type: 'Normal', power: 150, accuracy: 90, pp: 5, maxPp: 5 },
  quickAttack: { name: 'Quick Attack', type: 'Normal', power: 40, accuracy: 100, pp: 30, maxPp: 30 },
  confusion: { name: 'Confusion', type: 'Psychic', power: 50, accuracy: 100, pp: 25, maxPp: 25 },
  razorLeaf: { name: 'Razor Leaf', type: 'Grass', power: 55, accuracy: 95, pp: 25, maxPp: 25 },
  bubble: { name: 'Bubble', type: 'Water', power: 40, accuracy: 100, pp: 30, maxPp: 30 },
  peck: { name: 'Peck', type: 'Flying', power: 35, accuracy: 100, pp: 35, maxPp: 35 },
  gust: { name: 'Gust', type: 'Flying', power: 40, accuracy: 100, pp: 35, maxPp: 35 },
  poisonSting: { name: 'Poison Sting', type: 'Poison', power: 15, accuracy: 100, pp: 35, maxPp: 35 },
  rockThrow: { name: 'Rock Throw', type: 'Rock', power: 50, accuracy: 90, pp: 15, maxPp: 15 },
};

// Complete Kanto Pokedex (151 Pokemon)
export const POKEDEX: { [id: number]: PokedexEntry } = {
  1: {
    id: 1,
    name: 'Bulbasaur',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 45, attack: 49, defense: 49, specialAttack: 65, specialDefense: 65, speed: 45 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 7, move: MOVES.vineWhip },
      { level: 13, move: MOVES.razorLeaf },
    ],
    locations: ['Starter Pokemon from Professor Oak'],
    evolutionLevel: 16,
    evolutionTarget: 'Ivysaur',
  },
  2: {
    id: 2,
    name: 'Ivysaur',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 60, attack: 62, defense: 63, specialAttack: 80, specialDefense: 80, speed: 60 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 7, move: MOVES.vineWhip },
      { level: 13, move: MOVES.razorLeaf },
    ],
    locations: ['Evolve Bulbasaur'],
    evolutionLevel: 32,
    evolutionTarget: 'Venusaur',
  },
  3: {
    id: 3,
    name: 'Venusaur',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 80, attack: 82, defense: 83, specialAttack: 100, specialDefense: 100, speed: 80 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 7, move: MOVES.vineWhip },
      { level: 13, move: MOVES.razorLeaf },
      { level: 32, move: MOVES.solarBeam },
    ],
    locations: ['Evolve Ivysaur'],
  },
  4: {
    id: 4,
    name: 'Charmander',
    types: ['Fire'],
    baseStats: { hp: 39, attack: 52, defense: 43, specialAttack: 60, specialDefense: 50, speed: 65 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 7, move: MOVES.ember },
    ],
    locations: ['Starter Pokemon from Professor Oak'],
    evolutionLevel: 16,
    evolutionTarget: 'Charmeleon',
  },
  5: {
    id: 5,
    name: 'Charmeleon',
    types: ['Fire'],
    baseStats: { hp: 58, attack: 64, defense: 58, specialAttack: 80, specialDefense: 65, speed: 80 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 7, move: MOVES.ember },
    ],
    locations: ['Evolve Charmander'],
    evolutionLevel: 36,
    evolutionTarget: 'Charizard',
  },
  6: {
    id: 6,
    name: 'Charizard',
    types: ['Fire', 'Flying'],
    baseStats: { hp: 78, attack: 84, defense: 78, specialAttack: 109, specialDefense: 85, speed: 100 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 7, move: MOVES.ember },
      { level: 36, move: MOVES.flamethrower },
    ],
    locations: ['Evolve Charmeleon'],
  },
  7: {
    id: 7,
    name: 'Squirtle',
    types: ['Water'],
    baseStats: { hp: 44, attack: 48, defense: 65, specialAttack: 50, specialDefense: 64, speed: 43 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 7, move: MOVES.bubble },
      { level: 10, move: MOVES.waterGun },
    ],
    locations: ['Starter Pokemon from Professor Oak'],
    evolutionLevel: 16,
    evolutionTarget: 'Wartortle',
  },
  8: {
    id: 8,
    name: 'Wartortle',
    types: ['Water'],
    baseStats: { hp: 59, attack: 63, defense: 80, specialAttack: 65, specialDefense: 80, speed: 58 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 7, move: MOVES.bubble },
      { level: 10, move: MOVES.waterGun },
    ],
    locations: ['Evolve Squirtle'],
    evolutionLevel: 36,
    evolutionTarget: 'Blastoise',
  },
  9: {
    id: 9,
    name: 'Blastoise',
    types: ['Water'],
    baseStats: { hp: 79, attack: 83, defense: 100, specialAttack: 85, specialDefense: 105, speed: 78 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 7, move: MOVES.bubble },
      { level: 10, move: MOVES.waterGun },
      { level: 36, move: MOVES.hydroPump },
    ],
    locations: ['Evolve Wartortle'],
  },
  10: {
    id: 10,
    name: 'Caterpie',
    types: ['Bug'],
    baseStats: { hp: 45, attack: 30, defense: 35, specialAttack: 20, specialDefense: 20, speed: 45 },
    learnableMoves: [{ level: 1, move: MOVES.tackle }],
    locations: ['Route 2', 'Route 24', 'Route 25', 'Viridian Forest'],
    evolutionLevel: 7,
    evolutionTarget: 'Metapod',
  },
  11: {
    id: 11,
    name: 'Metapod',
    types: ['Bug'],
    baseStats: { hp: 50, attack: 20, defense: 55, specialAttack: 25, specialDefense: 25, speed: 30 },
    learnableMoves: [{ level: 1, move: MOVES.tackle }],
    locations: ['Route 24', 'Route 25', 'Viridian Forest', 'Evolve Caterpie'],
    evolutionLevel: 10,
    evolutionTarget: 'Butterfree',
  },
  12: {
    id: 12,
    name: 'Butterfree',
    types: ['Bug', 'Flying'],
    baseStats: { hp: 60, attack: 45, defense: 50, specialAttack: 90, specialDefense: 80, speed: 70 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 10, move: MOVES.confusion },
    ],
    locations: ['Evolve Metapod'],
  },
  13: {
    id: 13,
    name: 'Weedle',
    types: ['Bug', 'Poison'],
    baseStats: { hp: 40, attack: 35, defense: 30, specialAttack: 20, specialDefense: 20, speed: 50 },
    learnableMoves: [{ level: 1, move: MOVES.poisonSting }],
    locations: ['Route 2', 'Route 24', 'Route 25', 'Viridian Forest'],
    evolutionLevel: 7,
    evolutionTarget: 'Kakuna',
  },
  14: {
    id: 14,
    name: 'Kakuna',
    types: ['Bug', 'Poison'],
    baseStats: { hp: 45, attack: 25, defense: 50, specialAttack: 25, specialDefense: 25, speed: 35 },
    learnableMoves: [{ level: 1, move: MOVES.poisonSting }],
    locations: ['Route 24', 'Route 25', 'Viridian Forest', 'Evolve Weedle'],
    evolutionLevel: 10,
    evolutionTarget: 'Beedrill',
  },
  15: {
    id: 15,
    name: 'Beedrill',
    types: ['Bug', 'Poison'],
    baseStats: { hp: 65, attack: 90, defense: 40, specialAttack: 45, specialDefense: 80, speed: 75 },
    learnableMoves: [
      { level: 1, move: MOVES.poisonSting },
      { level: 10, move: MOVES.quickAttack },
    ],
    locations: ['Evolve Kakuna'],
  },
  16: {
    id: 16,
    name: 'Pidgey',
    types: ['Normal', 'Flying'],
    baseStats: { hp: 40, attack: 45, defense: 40, specialAttack: 35, specialDefense: 35, speed: 56 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 5, move: MOVES.gust },
    ],
    locations: ['Route 1', 'Route 2', 'Route 3', 'Route 5', 'Route 6', 'Route 7', 'Route 8', 'Route 12', 'Route 13', 'Route 14', 'Route 15'],
    evolutionLevel: 18,
    evolutionTarget: 'Pidgeotto',
  },
  17: {
    id: 17,
    name: 'Pidgeotto',
    types: ['Normal', 'Flying'],
    baseStats: { hp: 63, attack: 60, defense: 55, specialAttack: 50, specialDefense: 50, speed: 71 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 5, move: MOVES.gust },
    ],
    locations: ['Route 14', 'Route 15', 'Evolve Pidgey'],
    evolutionLevel: 36,
    evolutionTarget: 'Pidgeot',
  },
  18: {
    id: 18,
    name: 'Pidgeot',
    types: ['Normal', 'Flying'],
    baseStats: { hp: 83, attack: 80, defense: 75, specialAttack: 70, specialDefense: 70, speed: 101 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 5, move: MOVES.gust },
      { level: 36, move: MOVES.quickAttack },
    ],
    locations: ['Evolve Pidgeotto'],
  },
  19: {
    id: 19,
    name: 'Rattata',
    types: ['Normal'],
    baseStats: { hp: 30, attack: 56, defense: 35, specialAttack: 25, specialDefense: 35, speed: 72 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 7, move: MOVES.quickAttack },
      { level: 14, move: MOVES.bite },
    ],
    locations: ['Route 1', 'Route 2', 'Route 3', 'Route 4', 'Route 9', 'Route 10', 'Route 11', 'Route 16', 'Route 17', 'Route 18', 'Pokemon Mansion'],
    evolutionLevel: 20,
    evolutionTarget: 'Raticate',
  },
  20: {
    id: 20,
    name: 'Raticate',
    types: ['Normal'],
    baseStats: { hp: 55, attack: 81, defense: 60, specialAttack: 50, specialDefense: 70, speed: 97 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 7, move: MOVES.quickAttack },
      { level: 14, move: MOVES.bite },
    ],
    locations: ['Route 9', 'Route 10', 'Route 11', 'Route 16', 'Route 17', 'Route 18', 'Pokemon Mansion', 'Evolve Rattata'],
  },
  21: {
    id: 21,
    name: 'Spearow',
    types: ['Normal', 'Flying'],
    baseStats: { hp: 40, attack: 60, defense: 30, specialAttack: 31, specialDefense: 31, speed: 70 },
    learnableMoves: [
      { level: 1, move: MOVES.peck },
      { level: 9, move: MOVES.quickAttack },
    ],
    locations: ['Route 3', 'Route 4', 'Route 9', 'Route 10', 'Route 11', 'Route 16', 'Route 17', 'Route 18', 'Route 22', 'Route 23'],
    evolutionLevel: 20,
    evolutionTarget: 'Fearow',
  },
  22: {
    id: 22,
    name: 'Fearow',
    types: ['Normal', 'Flying'],
    baseStats: { hp: 65, attack: 90, defense: 65, specialAttack: 61, specialDefense: 61, speed: 100 },
    learnableMoves: [
      { level: 1, move: MOVES.peck },
      { level: 9, move: MOVES.quickAttack },
    ],
    locations: ['Route 9', 'Route 10', 'Route 17', 'Route 18', 'Route 23', 'Evolve Spearow'],
  },
  23: {
    id: 23,
    name: 'Ekans',
    types: ['Poison'],
    baseStats: { hp: 35, attack: 60, defense: 44, specialAttack: 40, specialDefense: 54, speed: 55 },
    learnableMoves: [
      { level: 1, move: MOVES.poisonSting },
      { level: 10, move: MOVES.bite },
    ],
    locations: ['Route 4', 'Route 8', 'Route 9', 'Route 10', 'Route 11', 'Route 23'],
    evolutionLevel: 22,
    evolutionTarget: 'Arbok',
  },
  24: {
    id: 24,
    name: 'Arbok',
    types: ['Poison'],
    baseStats: { hp: 60, attack: 95, defense: 69, specialAttack: 65, specialDefense: 79, speed: 80 },
    learnableMoves: [
      { level: 1, move: MOVES.poisonSting },
      { level: 10, move: MOVES.bite },
    ],
    locations: ['Route 23', 'Evolve Ekans'],
  },
  25: {
    id: 25,
    name: 'Pikachu',
    types: ['Electric'],
    baseStats: { hp: 35, attack: 55, defense: 40, specialAttack: 50, specialDefense: 50, speed: 90 },
    learnableMoves: [
      { level: 1, move: MOVES.thunderShock },
      { level: 8, move: MOVES.quickAttack },
      { level: 26, move: MOVES.thunderbolt },
    ],
    locations: ['Viridian Forest', 'Power Plant'],
    evolutionLevel: 26,
    evolutionTarget: 'Raichu',
  },
  26: {
    id: 26,
    name: 'Raichu',
    types: ['Electric'],
    baseStats: { hp: 60, attack: 90, defense: 55, specialAttack: 90, specialDefense: 80, speed: 110 },
    learnableMoves: [
      { level: 1, move: MOVES.thunderShock },
      { level: 26, move: MOVES.thunderbolt },
    ],
    locations: ['Evolve Pikachu'],
  },
  27: {
    id: 27,
    name: 'Sandshrew',
    types: ['Ground'],
    baseStats: { hp: 50, attack: 75, defense: 85, specialAttack: 20, specialDefense: 30, speed: 40 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 17, move: MOVES.earthquake },
    ],
    locations: ['Route 3', 'Route 4', 'Route 8', 'Route 9', 'Route 10', 'Route 11', 'Route 23'],
    evolutionLevel: 22,
    evolutionTarget: 'Sandslash',
  },
  28: {
    id: 28,
    name: 'Sandslash',
    types: ['Ground'],
    baseStats: { hp: 75, attack: 100, defense: 110, specialAttack: 45, specialDefense: 55, speed: 65 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 17, move: MOVES.earthquake },
    ],
    locations: ['Route 23', 'Evolve Sandshrew'],
  },
  29: {
    id: 29,
    name: 'Nidoran♀',
    types: ['Poison'],
    baseStats: { hp: 55, attack: 47, defense: 52, specialAttack: 40, specialDefense: 40, speed: 41 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 8, move: MOVES.poisonSting },
    ],
    locations: ['Route 22', 'Route 23', 'Safari Zone'],
    evolutionLevel: 16,
    evolutionTarget: 'Nidorina',
  },
  30: {
    id: 30,
    name: 'Nidorina',
    types: ['Poison'],
    baseStats: { hp: 70, attack: 62, defense: 67, specialAttack: 55, specialDefense: 55, speed: 56 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 8, move: MOVES.poisonSting },
    ],
    locations: ['Route 23', 'Safari Zone', 'Evolve Nidoran♀'],
  },
  31: {
    id: 31,
    name: 'Nidoqueen',
    types: ['Poison', 'Ground'],
    baseStats: { hp: 90, attack: 92, defense: 87, specialAttack: 75, specialDefense: 85, speed: 76 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 8, move: MOVES.poisonSting },
      { level: 23, move: MOVES.earthquake },
    ],
    locations: ['Evolve Nidorina with Moon Stone'],
  },
  32: {
    id: 32,
    name: 'Nidoran♂',
    types: ['Poison'],
    baseStats: { hp: 46, attack: 57, defense: 40, specialAttack: 40, specialDefense: 40, speed: 50 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 8, move: MOVES.poisonSting },
    ],
    locations: ['Route 22', 'Route 23', 'Safari Zone'],
    evolutionLevel: 16,
    evolutionTarget: 'Nidorino',
  },
  33: {
    id: 33,
    name: 'Nidorino',
    types: ['Poison'],
    baseStats: { hp: 61, attack: 72, defense: 57, specialAttack: 55, specialDefense: 55, speed: 65 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 8, move: MOVES.poisonSting },
    ],
    locations: ['Route 23', 'Safari Zone', 'Evolve Nidoran♂'],
  },
  34: {
    id: 34,
    name: 'Nidoking',
    types: ['Poison', 'Ground'],
    baseStats: { hp: 81, attack: 102, defense: 77, specialAttack: 85, specialDefense: 75, speed: 85 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 8, move: MOVES.poisonSting },
      { level: 23, move: MOVES.earthquake },
    ],
    locations: ['Evolve Nidorino with Moon Stone'],
  },
  35: {
    id: 35,
    name: 'Clefairy',
    types: ['Fairy'],
    baseStats: { hp: 70, attack: 45, defense: 48, specialAttack: 60, specialDefense: 65, speed: 35 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Mt. Moon'],
  },
  36: {
    id: 36,
    name: 'Clefable',
    types: ['Fairy'],
    baseStats: { hp: 95, attack: 70, defense: 73, specialAttack: 95, specialDefense: 90, speed: 60 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Evolve Clefairy with Moon Stone'],
  },
  37: {
    id: 37,
    name: 'Vulpix',
    types: ['Fire'],
    baseStats: { hp: 38, attack: 41, defense: 40, specialAttack: 50, specialDefense: 65, speed: 65 },
    learnableMoves: [
      { level: 1, move: MOVES.ember },
      { level: 16, move: MOVES.quickAttack },
    ],
    locations: ['Route 7', 'Route 8', 'Pokemon Mansion'],
  },
  38: {
    id: 38,
    name: 'Ninetales',
    types: ['Fire'],
    baseStats: { hp: 73, attack: 76, defense: 75, specialAttack: 81, specialDefense: 100, speed: 100 },
    learnableMoves: [
      { level: 1, move: MOVES.ember },
      { level: 16, move: MOVES.flamethrower },
    ],
    locations: ['Evolve Vulpix with Fire Stone'],
  },
  39: {
    id: 39,
    name: 'Jigglypuff',
    types: ['Normal', 'Fairy'],
    baseStats: { hp: 115, attack: 45, defense: 20, specialAttack: 45, specialDefense: 25, speed: 20 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Route 3', 'Route 4', 'Route 5', 'Route 6', 'Route 7', 'Route 8'],
  },
  40: {
    id: 40,
    name: 'Wigglytuff',
    types: ['Normal', 'Fairy'],
    baseStats: { hp: 140, attack: 70, defense: 45, specialAttack: 85, specialDefense: 50, speed: 45 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Evolve Jigglypuff with Moon Stone'],
  },
  41: {
    id: 41,
    name: 'Zubat',
    types: ['Poison', 'Flying'],
    baseStats: { hp: 40, attack: 45, defense: 35, specialAttack: 30, specialDefense: 40, speed: 55 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 10, move: MOVES.bite },
    ],
    locations: ['Mt. Moon', 'Rock Tunnel', 'Seafoam Islands', 'Victory Road', 'Pokemon Tower'],
    evolutionLevel: 22,
    evolutionTarget: 'Golbat',
  },
  42: {
    id: 42,
    name: 'Golbat',
    types: ['Poison', 'Flying'],
    baseStats: { hp: 75, attack: 80, defense: 70, specialAttack: 65, specialDefense: 75, speed: 90 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 10, move: MOVES.bite },
    ],
    locations: ['Seafoam Islands', 'Victory Road', 'Cerulean Cave', 'Evolve Zubat'],
  },
  43: {
    id: 43,
    name: 'Oddish',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 45, attack: 50, defense: 55, specialAttack: 75, specialDefense: 65, speed: 30 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 15, move: MOVES.poisonSting },
    ],
    locations: ['Route 5', 'Route 6', 'Route 7', 'Route 12', 'Route 13', 'Route 14', 'Route 15', 'Route 24', 'Route 25'],
    evolutionLevel: 21,
    evolutionTarget: 'Gloom',
  },
  44: {
    id: 44,
    name: 'Gloom',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 60, attack: 65, defense: 70, specialAttack: 85, specialDefense: 75, speed: 40 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 15, move: MOVES.poisonSting },
    ],
    locations: ['Route 12', 'Route 13', 'Route 14', 'Route 15', 'Evolve Oddish'],
  },
  45: {
    id: 45,
    name: 'Vileplume',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 75, attack: 80, defense: 85, specialAttack: 110, specialDefense: 90, speed: 50 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 15, move: MOVES.poisonSting },
      { level: 44, move: MOVES.solarBeam },
    ],
    locations: ['Evolve Gloom with Leaf Stone'],
  },
  46: {
    id: 46,
    name: 'Paras',
    types: ['Bug', 'Grass'],
    baseStats: { hp: 35, attack: 70, defense: 55, specialAttack: 45, specialDefense: 55, speed: 25 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
    ],
    locations: ['Mt. Moon', 'Safari Zone'],
    evolutionLevel: 24,
    evolutionTarget: 'Parasect',
  },
  47: {
    id: 47,
    name: 'Parasect',
    types: ['Bug', 'Grass'],
    baseStats: { hp: 60, attack: 95, defense: 80, specialAttack: 60, specialDefense: 80, speed: 30 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
    ],
    locations: ['Safari Zone', 'Cerulean Cave', 'Evolve Paras'],
  },
  48: {
    id: 48,
    name: 'Venonat',
    types: ['Bug', 'Poison'],
    baseStats: { hp: 60, attack: 55, defense: 50, specialAttack: 40, specialDefense: 55, speed: 45 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 11, move: MOVES.confusion },
    ],
    locations: ['Route 12', 'Route 13', 'Route 14', 'Route 15', 'Safari Zone'],
    evolutionLevel: 31,
    evolutionTarget: 'Venomoth',
  },
  49: {
    id: 49,
    name: 'Venomoth',
    types: ['Bug', 'Poison'],
    baseStats: { hp: 70, attack: 65, defense: 60, specialAttack: 90, specialDefense: 75, speed: 90 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 11, move: MOVES.confusion },
      { level: 31, move: MOVES.psychic },
    ],
    locations: ['Safari Zone', 'Evolve Venonat'],
  },
  50: {
    id: 50,
    name: 'Diglett',
    types: ['Ground'],
    baseStats: { hp: 10, attack: 55, defense: 25, specialAttack: 35, specialDefense: 45, speed: 95 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 15, move: MOVES.earthquake },
    ],
    locations: ['Digletts Cave'],
    evolutionLevel: 26,
    evolutionTarget: 'Dugtrio',
  },
  51: {
    id: 51,
    name: 'Dugtrio',
    types: ['Ground'],
    baseStats: { hp: 35, attack: 100, defense: 50, specialAttack: 50, specialDefense: 70, speed: 120 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 15, move: MOVES.earthquake },
    ],
    locations: ['Digletts Cave', 'Evolve Diglett'],
  },
  52: {
    id: 52,
    name: 'Meowth',
    types: ['Normal'],
    baseStats: { hp: 40, attack: 45, defense: 35, specialAttack: 40, specialDefense: 40, speed: 90 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 12, move: MOVES.bite },
    ],
    locations: ['Route 5', 'Route 6', 'Route 7', 'Route 8'],
    evolutionLevel: 28,
    evolutionTarget: 'Persian',
  },
  53: {
    id: 53,
    name: 'Persian',
    types: ['Normal'],
    baseStats: { hp: 65, attack: 70, defense: 60, specialAttack: 65, specialDefense: 65, speed: 115 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 12, move: MOVES.bite },
    ],
    locations: ['Evolve Meowth'],
  },
  54: {
    id: 54,
    name: 'Psyduck',
    types: ['Water'],
    baseStats: { hp: 50, attack: 52, defense: 48, specialAttack: 65, specialDefense: 50, speed: 55 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 10, move: MOVES.waterGun },
      { level: 28, move: MOVES.confusion },
    ],
    locations: ['Route 4', 'Route 6', 'Route 11', 'Route 13', 'Route 17', 'Route 18', 'Route 22', 'Route 23', 'Cerulean Cave'],
    evolutionLevel: 33,
    evolutionTarget: 'Golduck',
  },
  55: {
    id: 55,
    name: 'Golduck',
    types: ['Water'],
    baseStats: { hp: 80, attack: 82, defense: 78, specialAttack: 95, specialDefense: 80, speed: 85 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 10, move: MOVES.waterGun },
      { level: 28, move: MOVES.confusion },
      { level: 33, move: MOVES.psychic },
    ],
    locations: ['Route 6', 'Route 22', 'Route 23', 'Cerulean Cave', 'Evolve Psyduck'],
  },
  56: {
    id: 56,
    name: 'Mankey',
    types: ['Fighting'],
    baseStats: { hp: 40, attack: 80, defense: 35, specialAttack: 35, specialDefense: 45, speed: 70 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 9, move: MOVES.quickAttack },
    ],
    locations: ['Route 3', 'Route 4', 'Route 22', 'Route 23'],
    evolutionLevel: 28,
    evolutionTarget: 'Primeape',
  },
  57: {
    id: 57,
    name: 'Primeape',
    types: ['Fighting'],
    baseStats: { hp: 65, attack: 105, defense: 60, specialAttack: 60, specialDefense: 70, speed: 95 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 9, move: MOVES.quickAttack },
    ],
    locations: ['Route 23', 'Evolve Mankey'],
  },
  58: {
    id: 58,
    name: 'Growlithe',
    types: ['Fire'],
    baseStats: { hp: 55, attack: 70, defense: 45, specialAttack: 70, specialDefense: 50, speed: 60 },
    learnableMoves: [
      { level: 1, move: MOVES.bite },
      { level: 18, move: MOVES.ember },
    ],
    locations: ['Route 7', 'Route 8', 'Pokemon Mansion'],
  },
  59: {
    id: 59,
    name: 'Arcanine',
    types: ['Fire'],
    baseStats: { hp: 90, attack: 110, defense: 80, specialAttack: 100, specialDefense: 80, speed: 95 },
    learnableMoves: [
      { level: 1, move: MOVES.bite },
      { level: 18, move: MOVES.flamethrower },
    ],
    locations: ['Evolve Growlithe with Fire Stone'],
  },
  60: {
    id: 60,
    name: 'Poliwag',
    types: ['Water'],
    baseStats: { hp: 40, attack: 50, defense: 40, specialAttack: 40, specialDefense: 40, speed: 90 },
    learnableMoves: [
      { level: 1, move: MOVES.bubble },
      { level: 16, move: MOVES.waterGun },
    ],
    locations: ['Route 6', 'Route 22', 'Route 23', 'Viridian City', 'Pallet Town', 'Cerulean City'],
    evolutionLevel: 25,
    evolutionTarget: 'Poliwhirl',
  },
  61: {
    id: 61,
    name: 'Poliwhirl',
    types: ['Water'],
    baseStats: { hp: 65, attack: 65, defense: 65, specialAttack: 50, specialDefense: 50, speed: 90 },
    learnableMoves: [
      { level: 1, move: MOVES.bubble },
      { level: 16, move: MOVES.waterGun },
    ],
    locations: ['Route 6', 'Route 22', 'Route 23', 'Cerulean City', 'Evolve Poliwag'],
  },
  62: {
    id: 62,
    name: 'Poliwrath',
    types: ['Water', 'Fighting'],
    baseStats: { hp: 90, attack: 95, defense: 95, specialAttack: 70, specialDefense: 90, speed: 70 },
    learnableMoves: [
      { level: 1, move: MOVES.bubble },
      { level: 16, move: MOVES.waterGun },
      { level: 35, move: MOVES.surf },
    ],
    locations: ['Evolve Poliwhirl with Water Stone'],
  },
  63: {
    id: 63,
    name: 'Abra',
    types: ['Psychic'],
    baseStats: { hp: 25, attack: 20, defense: 15, specialAttack: 105, specialDefense: 55, speed: 90 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Route 5', 'Route 6', 'Route 7', 'Route 8'],
    evolutionLevel: 16,
    evolutionTarget: 'Kadabra',
  },
  64: {
    id: 64,
    name: 'Kadabra',
    types: ['Psychic'],
    baseStats: { hp: 40, attack: 35, defense: 30, specialAttack: 120, specialDefense: 70, speed: 105 },
    learnableMoves: [
      { level: 1, move: MOVES.confusion },
      { level: 16, move: MOVES.psychic },
    ],
    locations: ['Cerulean Cave', 'Evolve Abra'],
  },
  65: {
    id: 65,
    name: 'Alakazam',
    types: ['Psychic'],
    baseStats: { hp: 55, attack: 50, defense: 45, specialAttack: 135, specialDefense: 95, speed: 120 },
    learnableMoves: [
      { level: 1, move: MOVES.confusion },
      { level: 16, move: MOVES.psychic },
    ],
    locations: ['Trade Kadabra'],
  },
  66: {
    id: 66,
    name: 'Machop',
    types: ['Fighting'],
    baseStats: { hp: 70, attack: 80, defense: 50, specialAttack: 35, specialDefense: 35, speed: 35 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Rock Tunnel', 'Victory Road'],
    evolutionLevel: 28,
    evolutionTarget: 'Machoke',
  },
  67: {
    id: 67,
    name: 'Machoke',
    types: ['Fighting'],
    baseStats: { hp: 80, attack: 100, defense: 70, specialAttack: 50, specialDefense: 60, speed: 45 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Victory Road', 'Cerulean Cave', 'Evolve Machop'],
  },
  68: {
    id: 68,
    name: 'Machamp',
    types: ['Fighting'],
    baseStats: { hp: 90, attack: 130, defense: 80, specialAttack: 65, specialDefense: 85, speed: 55 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Trade Machoke'],
  },
  69: {
    id: 69,
    name: 'Bellsprout',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 50, attack: 75, defense: 35, specialAttack: 70, specialDefense: 30, speed: 40 },
    learnableMoves: [
      { level: 1, move: MOVES.vineWhip },
      { level: 13, move: MOVES.poisonSting },
    ],
    locations: ['Route 5', 'Route 6', 'Route 7', 'Route 12', 'Route 13', 'Route 14', 'Route 15', 'Route 24', 'Route 25'],
    evolutionLevel: 21,
    evolutionTarget: 'Weepinbell',
  },
  70: {
    id: 70,
    name: 'Weepinbell',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 65, attack: 90, defense: 50, specialAttack: 85, specialDefense: 45, speed: 55 },
    learnableMoves: [
      { level: 1, move: MOVES.vineWhip },
      { level: 13, move: MOVES.poisonSting },
    ],
    locations: ['Route 12', 'Route 13', 'Route 14', 'Route 15', 'Evolve Bellsprout'],
  },
  71: {
    id: 71,
    name: 'Victreebel',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 80, attack: 105, defense: 65, specialAttack: 100, specialDefense: 70, speed: 70 },
    learnableMoves: [
      { level: 1, move: MOVES.vineWhip },
      { level: 13, move: MOVES.poisonSting },
      { level: 42, move: MOVES.razorLeaf },
    ],
    locations: ['Evolve Weepinbell with Leaf Stone'],
  },
  72: {
    id: 72,
    name: 'Tentacool',
    types: ['Water', 'Poison'],
    baseStats: { hp: 40, attack: 40, defense: 35, specialAttack: 50, specialDefense: 100, speed: 70 },
    learnableMoves: [
      { level: 1, move: MOVES.poisonSting },
      { level: 7, move: MOVES.waterGun },
    ],
    locations: ['Route 19', 'Route 20', 'Route 21', 'Seafoam Islands'],
    evolutionLevel: 30,
    evolutionTarget: 'Tentacruel',
  },
  73: {
    id: 73,
    name: 'Tentacruel',
    types: ['Water', 'Poison'],
    baseStats: { hp: 80, attack: 70, defense: 65, specialAttack: 80, specialDefense: 120, speed: 100 },
    learnableMoves: [
      { level: 1, move: MOVES.poisonSting },
      { level: 7, move: MOVES.waterGun },
      { level: 30, move: MOVES.surf },
    ],
    locations: ['Route 19', 'Route 20', 'Route 21', 'Seafoam Islands', 'Evolve Tentacool'],
  },
  74: {
    id: 74,
    name: 'Geodude',
    types: ['Rock', 'Ground'],
    baseStats: { hp: 40, attack: 80, defense: 100, specialAttack: 30, specialDefense: 30, speed: 20 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 11, move: MOVES.rockThrow },
    ],
    locations: ['Mt. Moon', 'Rock Tunnel', 'Victory Road'],
    evolutionLevel: 25,
    evolutionTarget: 'Graveler',
  },
  75: {
    id: 75,
    name: 'Graveler',
    types: ['Rock', 'Ground'],
    baseStats: { hp: 55, attack: 95, defense: 115, specialAttack: 45, specialDefense: 45, speed: 35 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 11, move: MOVES.rockThrow },
      { level: 25, move: MOVES.earthquake },
    ],
    locations: ['Rock Tunnel', 'Victory Road', 'Cerulean Cave', 'Evolve Geodude'],
    evolutionLevel: 40,
    evolutionTarget: 'Golem',
  },
  76: {
    id: 76,
    name: 'Golem',
    types: ['Rock', 'Ground'],
    baseStats: { hp: 80, attack: 120, defense: 130, specialAttack: 55, specialDefense: 65, speed: 45 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 11, move: MOVES.rockThrow },
      { level: 25, move: MOVES.earthquake },
    ],
    locations: ['Evolve Graveler'],
  },
  77: {
    id: 77,
    name: 'Ponyta',
    types: ['Fire'],
    baseStats: { hp: 50, attack: 85, defense: 55, specialAttack: 65, specialDefense: 65, speed: 90 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 30, move: MOVES.ember },
    ],
    locations: ['Route 7', 'Route 8', 'Pokemon Mansion'],
    evolutionLevel: 40,
    evolutionTarget: 'Rapidash',
  },
  78: {
    id: 78,
    name: 'Rapidash',
    types: ['Fire'],
    baseStats: { hp: 65, attack: 100, defense: 70, specialAttack: 80, specialDefense: 80, speed: 105 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 30, move: MOVES.ember },
      { level: 40, move: MOVES.flamethrower },
    ],
    locations: ['Evolve Ponyta'],
  },
  79: {
    id: 79,
    name: 'Slowpoke',
    types: ['Water', 'Psychic'],
    baseStats: { hp: 90, attack: 65, defense: 65, specialAttack: 40, specialDefense: 40, speed: 15 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 18, move: MOVES.waterGun },
      { level: 22, move: MOVES.confusion },
    ],
    locations: ['Route 10', 'Route 23', 'Seafoam Islands'],
    evolutionLevel: 37,
    evolutionTarget: 'Slowbro',
  },
  80: {
    id: 80,
    name: 'Slowbro',
    types: ['Water', 'Psychic'],
    baseStats: { hp: 95, attack: 75, defense: 110, specialAttack: 100, specialDefense: 80, speed: 30 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 18, move: MOVES.waterGun },
      { level: 22, move: MOVES.confusion },
      { level: 37, move: MOVES.psychic },
    ],
    locations: ['Seafoam Islands', 'Cerulean Cave', 'Evolve Slowpoke'],
  },
  81: {
    id: 81,
    name: 'Magnemite',
    types: ['Electric', 'Steel'],
    baseStats: { hp: 25, attack: 35, defense: 70, specialAttack: 95, specialDefense: 55, speed: 45 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 21, move: MOVES.thunderShock },
    ],
    locations: ['Power Plant'],
    evolutionLevel: 30,
    evolutionTarget: 'Magneton',
  },
  82: {
    id: 82,
    name: 'Magneton',
    types: ['Electric', 'Steel'],
    baseStats: { hp: 50, attack: 60, defense: 95, specialAttack: 120, specialDefense: 70, speed: 70 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 21, move: MOVES.thunderShock },
      { level: 30, move: MOVES.thunderbolt },
    ],
    locations: ['Power Plant', 'Cerulean Cave', 'Evolve Magnemite'],
  },
  83: {
    id: 83,
    name: "Farfetch'd",
    types: ['Normal', 'Flying'],
    baseStats: { hp: 52, attack: 90, defense: 55, specialAttack: 58, specialDefense: 62, speed: 60 },
    learnableMoves: [
      { level: 1, move: MOVES.peck },
    ],
    locations: ['Route 12', 'Route 13'],
  },
  84: {
    id: 84,
    name: 'Doduo',
    types: ['Normal', 'Flying'],
    baseStats: { hp: 35, attack: 85, defense: 45, specialAttack: 35, specialDefense: 35, speed: 75 },
    learnableMoves: [
      { level: 1, move: MOVES.peck },
      { level: 20, move: MOVES.quickAttack },
    ],
    locations: ['Route 16', 'Route 17', 'Route 18'],
    evolutionLevel: 31,
    evolutionTarget: 'Dodrio',
  },
  85: {
    id: 85,
    name: 'Dodrio',
    types: ['Normal', 'Flying'],
    baseStats: { hp: 60, attack: 110, defense: 70, specialAttack: 60, specialDefense: 60, speed: 110 },
    learnableMoves: [
      { level: 1, move: MOVES.peck },
      { level: 20, move: MOVES.quickAttack },
    ],
    locations: ['Route 17', 'Evolve Doduo'],
  },
  86: {
    id: 86,
    name: 'Seel',
    types: ['Water'],
    baseStats: { hp: 65, attack: 45, defense: 55, specialAttack: 45, specialDefense: 70, speed: 45 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 16, move: MOVES.waterGun },
    ],
    locations: ['Seafoam Islands'],
    evolutionLevel: 34,
    evolutionTarget: 'Dewgong',
  },
  87: {
    id: 87,
    name: 'Dewgong',
    types: ['Water', 'Ice'],
    baseStats: { hp: 90, attack: 70, defense: 80, specialAttack: 70, specialDefense: 95, speed: 70 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 16, move: MOVES.waterGun },
      { level: 34, move: MOVES.iceBeam },
    ],
    locations: ['Seafoam Islands', 'Evolve Seel'],
  },
  88: {
    id: 88,
    name: 'Grimer',
    types: ['Poison'],
    baseStats: { hp: 80, attack: 80, defense: 50, specialAttack: 40, specialDefense: 50, speed: 25 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 8, move: MOVES.poisonSting },
    ],
    locations: ['Pokemon Mansion', 'Cinnabar Island'],
    evolutionLevel: 38,
    evolutionTarget: 'Muk',
  },
  89: {
    id: 89,
    name: 'Muk',
    types: ['Poison'],
    baseStats: { hp: 105, attack: 105, defense: 75, specialAttack: 65, specialDefense: 100, speed: 50 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 8, move: MOVES.poisonSting },
    ],
    locations: ['Pokemon Mansion', 'Cinnabar Island', 'Cerulean Cave', 'Evolve Grimer'],
  },
  90: {
    id: 90,
    name: 'Shellder',
    types: ['Water'],
    baseStats: { hp: 30, attack: 65, defense: 100, specialAttack: 45, specialDefense: 25, speed: 40 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 18, move: MOVES.waterGun },
    ],
    locations: ['Route 6', 'Route 11', 'Vermilion City', 'Cinnabar Island'],
  },
  91: {
    id: 91,
    name: 'Cloyster',
    types: ['Water', 'Ice'],
    baseStats: { hp: 50, attack: 95, defense: 180, specialAttack: 85, specialDefense: 45, speed: 70 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 18, move: MOVES.iceBeam },
    ],
    locations: ['Evolve Shellder with Water Stone'],
  },
  92: {
    id: 92,
    name: 'Gastly',
    types: ['Ghost', 'Poison'],
    baseStats: { hp: 30, attack: 35, defense: 30, specialAttack: 100, specialDefense: 35, speed: 80 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 8, move: MOVES.confusion },
    ],
    locations: ['Pokemon Tower'],
    evolutionLevel: 25,
    evolutionTarget: 'Haunter',
  },
  93: {
    id: 93,
    name: 'Haunter',
    types: ['Ghost', 'Poison'],
    baseStats: { hp: 45, attack: 50, defense: 45, specialAttack: 115, specialDefense: 55, speed: 95 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 8, move: MOVES.confusion },
      { level: 25, move: MOVES.psychic },
    ],
    locations: ['Pokemon Tower', 'Evolve Gastly'],
  },
  94: {
    id: 94,
    name: 'Gengar',
    types: ['Ghost', 'Poison'],
    baseStats: { hp: 60, attack: 65, defense: 60, specialAttack: 130, specialDefense: 75, speed: 110 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 8, move: MOVES.confusion },
      { level: 25, move: MOVES.psychic },
    ],
    locations: ['Trade Haunter'],
  },
  95: {
    id: 95,
    name: 'Onix',
    types: ['Rock', 'Ground'],
    baseStats: { hp: 35, attack: 45, defense: 160, specialAttack: 30, specialDefense: 45, speed: 70 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 15, move: MOVES.rockThrow },
    ],
    locations: ['Rock Tunnel', 'Victory Road'],
  },
  96: {
    id: 96,
    name: 'Drowzee',
    types: ['Psychic'],
    baseStats: { hp: 60, attack: 48, defense: 45, specialAttack: 43, specialDefense: 90, speed: 42 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 12, move: MOVES.confusion },
    ],
    locations: ['Route 11'],
    evolutionLevel: 26,
    evolutionTarget: 'Hypno',
  },
  97: {
    id: 97,
    name: 'Hypno',
    types: ['Psychic'],
    baseStats: { hp: 85, attack: 73, defense: 70, specialAttack: 73, specialDefense: 115, speed: 67 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 12, move: MOVES.confusion },
      { level: 26, move: MOVES.psychic },
    ],
    locations: ['Cerulean Cave', 'Evolve Drowzee'],
  },
  98: {
    id: 98,
    name: 'Krabby',
    types: ['Water'],
    baseStats: { hp: 30, attack: 105, defense: 90, specialAttack: 25, specialDefense: 25, speed: 50 },
    learnableMoves: [
      { level: 1, move: MOVES.bubble },
      { level: 12, move: MOVES.waterGun },
    ],
    locations: ['Route 4', 'Route 6', 'Route 11', 'Route 12', 'Route 13', 'Route 17', 'Route 18', 'Route 19', 'Route 21', 'Vermilion City', 'Fuchsia City'],
    evolutionLevel: 28,
    evolutionTarget: 'Kingler',
  },
  99: {
    id: 99,
    name: 'Kingler',
    types: ['Water'],
    baseStats: { hp: 55, attack: 130, defense: 115, specialAttack: 50, specialDefense: 50, speed: 75 },
    learnableMoves: [
      { level: 1, move: MOVES.bubble },
      { level: 12, move: MOVES.waterGun },
    ],
    locations: ['Route 23', 'Evolve Krabby'],
  },
  100: {
    id: 100,
    name: 'Voltorb',
    types: ['Electric'],
    baseStats: { hp: 40, attack: 30, defense: 50, specialAttack: 55, specialDefense: 55, speed: 100 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 17, move: MOVES.thunderShock },
    ],
    locations: ['Power Plant', 'Route 10'],
    evolutionLevel: 30,
    evolutionTarget: 'Electrode',
  },
  101: {
    id: 101,
    name: 'Electrode',
    types: ['Electric'],
    baseStats: { hp: 60, attack: 50, defense: 70, specialAttack: 80, specialDefense: 80, speed: 150 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 17, move: MOVES.thunderShock },
      { level: 30, move: MOVES.thunderbolt },
    ],
    locations: ['Power Plant', 'Cerulean Cave', 'Evolve Voltorb'],
  },
  102: {
    id: 102,
    name: 'Exeggcute',
    types: ['Grass', 'Psychic'],
    baseStats: { hp: 60, attack: 40, defense: 80, specialAttack: 60, specialDefense: 45, speed: 40 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 11, move: MOVES.confusion },
    ],
    locations: ['Safari Zone'],
  },
  103: {
    id: 103,
    name: 'Exeggutor',
    types: ['Grass', 'Psychic'],
    baseStats: { hp: 95, attack: 95, defense: 85, specialAttack: 125, specialDefense: 75, speed: 55 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 11, move: MOVES.confusion },
      { level: 28, move: MOVES.psychic },
    ],
    locations: ['Evolve Exeggcute with Leaf Stone'],
  },
  104: {
    id: 104,
    name: 'Cubone',
    types: ['Ground'],
    baseStats: { hp: 50, attack: 50, defense: 95, specialAttack: 40, specialDefense: 50, speed: 35 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Pokemon Tower', 'Route 10', 'Route 11'],
    evolutionLevel: 28,
    evolutionTarget: 'Marowak',
  },
  105: {
    id: 105,
    name: 'Marowak',
    types: ['Ground'],
    baseStats: { hp: 60, attack: 80, defense: 110, specialAttack: 50, specialDefense: 80, speed: 45 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 28, move: MOVES.earthquake },
    ],
    locations: ['Victory Road', 'Evolve Cubone'],
  },
  106: {
    id: 106,
    name: 'Hitmonlee',
    types: ['Fighting'],
    baseStats: { hp: 50, attack: 120, defense: 53, specialAttack: 35, specialDefense: 110, speed: 87 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Saffron City Fighting Dojo'],
  },
  107: {
    id: 107,
    name: 'Hitmonchan',
    types: ['Fighting'],
    baseStats: { hp: 50, attack: 105, defense: 79, specialAttack: 35, specialDefense: 110, speed: 76 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Saffron City Fighting Dojo'],
  },
  108: {
    id: 108,
    name: 'Lickitung',
    types: ['Normal'],
    baseStats: { hp: 90, attack: 55, defense: 75, specialAttack: 60, specialDefense: 75, speed: 30 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Route 18'],
  },
  109: {
    id: 109,
    name: 'Koffing',
    types: ['Poison'],
    baseStats: { hp: 40, attack: 65, defense: 95, specialAttack: 60, specialDefense: 45, speed: 35 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 9, move: MOVES.poisonSting },
    ],
    locations: ['Pokemon Mansion'],
    evolutionLevel: 35,
    evolutionTarget: 'Weezing',
  },
  110: {
    id: 110,
    name: 'Weezing',
    types: ['Poison'],
    baseStats: { hp: 65, attack: 90, defense: 120, specialAttack: 85, specialDefense: 70, speed: 60 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 9, move: MOVES.poisonSting },
    ],
    locations: ['Pokemon Mansion', 'Evolve Koffing'],
  },
  111: {
    id: 111,
    name: 'Rhyhorn',
    types: ['Ground', 'Rock'],
    baseStats: { hp: 80, attack: 85, defense: 95, specialAttack: 30, specialDefense: 30, speed: 25 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 30, move: MOVES.rockThrow },
    ],
    locations: ['Safari Zone'],
    evolutionLevel: 42,
    evolutionTarget: 'Rhydon',
  },
  112: {
    id: 112,
    name: 'Rhydon',
    types: ['Ground', 'Rock'],
    baseStats: { hp: 105, attack: 130, defense: 120, specialAttack: 45, specialDefense: 45, speed: 40 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 30, move: MOVES.rockThrow },
      { level: 42, move: MOVES.earthquake },
    ],
    locations: ['Victory Road', 'Cerulean Cave', 'Evolve Rhyhorn'],
  },
  113: {
    id: 113,
    name: 'Chansey',
    types: ['Normal'],
    baseStats: { hp: 250, attack: 5, defense: 5, specialAttack: 35, specialDefense: 105, speed: 50 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Safari Zone', 'Cerulean Cave'],
  },
  114: {
    id: 114,
    name: 'Tangela',
    types: ['Grass'],
    baseStats: { hp: 65, attack: 55, defense: 115, specialAttack: 100, specialDefense: 40, speed: 60 },
    learnableMoves: [
      { level: 1, move: MOVES.vineWhip },
      { level: 29, move: MOVES.razorLeaf },
    ],
    locations: ['Route 21'],
  },
  115: {
    id: 115,
    name: 'Kangaskhan',
    types: ['Normal'],
    baseStats: { hp: 105, attack: 95, defense: 80, specialAttack: 40, specialDefense: 80, speed: 90 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Safari Zone'],
  },
  116: {
    id: 116,
    name: 'Horsea',
    types: ['Water'],
    baseStats: { hp: 30, attack: 40, defense: 70, specialAttack: 70, specialDefense: 25, speed: 60 },
    learnableMoves: [
      { level: 1, move: MOVES.bubble },
      { level: 19, move: MOVES.waterGun },
    ],
    locations: ['Route 19', 'Route 20', 'Route 21', 'Seafoam Islands', 'Cinnabar Island'],
    evolutionLevel: 32,
    evolutionTarget: 'Seadra',
  },
  117: {
    id: 117,
    name: 'Seadra',
    types: ['Water'],
    baseStats: { hp: 55, attack: 65, defense: 95, specialAttack: 95, specialDefense: 45, speed: 85 },
    learnableMoves: [
      { level: 1, move: MOVES.bubble },
      { level: 19, move: MOVES.waterGun },
    ],
    locations: ['Route 20', 'Seafoam Islands', 'Cinnabar Island', 'Evolve Horsea'],
  },
  118: {
    id: 118,
    name: 'Goldeen',
    types: ['Water'],
    baseStats: { hp: 45, attack: 67, defense: 60, specialAttack: 35, specialDefense: 50, speed: 63 },
    learnableMoves: [
      { level: 1, move: MOVES.peck },
      { level: 15, move: MOVES.waterGun },
    ],
    locations: ['Route 6', 'Route 10', 'Route 11', 'Route 12', 'Route 13', 'Route 22', 'Route 23', 'Cerulean City', 'Fuchsia City'],
    evolutionLevel: 33,
    evolutionTarget: 'Seaking',
  },
  119: {
    id: 119,
    name: 'Seaking',
    types: ['Water'],
    baseStats: { hp: 80, attack: 92, defense: 65, specialAttack: 65, specialDefense: 80, speed: 68 },
    learnableMoves: [
      { level: 1, move: MOVES.peck },
      { level: 15, move: MOVES.waterGun },
    ],
    locations: ['Route 23', 'Fuchsia City', 'Evolve Goldeen'],
  },
  120: {
    id: 120,
    name: 'Staryu',
    types: ['Water'],
    baseStats: { hp: 30, attack: 45, defense: 55, specialAttack: 70, specialDefense: 55, speed: 85 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 17, move: MOVES.waterGun },
    ],
    locations: ['Route 19', 'Route 21', 'Cinnabar Island', 'Cerulean City'],
  },
  121: {
    id: 121,
    name: 'Starmie',
    types: ['Water', 'Psychic'],
    baseStats: { hp: 60, attack: 75, defense: 85, specialAttack: 100, specialDefense: 85, speed: 115 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 17, move: MOVES.waterGun },
      { level: 28, move: MOVES.psychic },
    ],
    locations: ['Evolve Staryu with Water Stone'],
  },
  122: {
    id: 122,
    name: 'Mr. Mime',
    types: ['Psychic', 'Fairy'],
    baseStats: { hp: 40, attack: 45, defense: 65, specialAttack: 100, specialDefense: 120, speed: 90 },
    learnableMoves: [
      { level: 1, move: MOVES.confusion },
      { level: 15, move: MOVES.psychic },
    ],
    locations: ['Route 11'],
  },
  123: {
    id: 123,
    name: 'Scyther',
    types: ['Bug', 'Flying'],
    baseStats: { hp: 70, attack: 110, defense: 80, specialAttack: 55, specialDefense: 80, speed: 105 },
    learnableMoves: [
      { level: 1, move: MOVES.quickAttack },
    ],
    locations: ['Safari Zone'],
  },
  124: {
    id: 124,
    name: 'Jynx',
    types: ['Ice', 'Psychic'],
    baseStats: { hp: 65, attack: 50, defense: 35, specialAttack: 115, specialDefense: 95, speed: 95 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 18, move: MOVES.confusion },
      { level: 31, move: MOVES.psychic },
    ],
    locations: ['Cerulean Cave'],
  },
  125: {
    id: 125,
    name: 'Electabuzz',
    types: ['Electric'],
    baseStats: { hp: 65, attack: 83, defense: 57, specialAttack: 95, specialDefense: 85, speed: 105 },
    learnableMoves: [
      { level: 1, move: MOVES.quickAttack },
      { level: 34, move: MOVES.thunderbolt },
    ],
    locations: ['Power Plant'],
  },
  126: {
    id: 126,
    name: 'Magmar',
    types: ['Fire'],
    baseStats: { hp: 65, attack: 95, defense: 57, specialAttack: 100, specialDefense: 85, speed: 93 },
    learnableMoves: [
      { level: 1, move: MOVES.ember },
      { level: 36, move: MOVES.flamethrower },
    ],
    locations: ['Pokemon Mansion'],
  },
  127: {
    id: 127,
    name: 'Pinsir',
    types: ['Bug'],
    baseStats: { hp: 65, attack: 125, defense: 100, specialAttack: 55, specialDefense: 70, speed: 85 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Safari Zone'],
  },
  128: {
    id: 128,
    name: 'Tauros',
    types: ['Normal'],
    baseStats: { hp: 75, attack: 100, defense: 95, specialAttack: 40, specialDefense: 70, speed: 110 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Safari Zone'],
  },
  129: {
    id: 129,
    name: 'Magikarp',
    types: ['Water'],
    baseStats: { hp: 20, attack: 10, defense: 55, specialAttack: 15, specialDefense: 20, speed: 80 },
    learnableMoves: [{ level: 1, move: MOVES.tackle }],
    locations: ['Any fishing spot'],
    evolutionLevel: 20,
    evolutionTarget: 'Gyarados',
  },
  130: {
    id: 130,
    name: 'Gyarados',
    types: ['Water', 'Flying'],
    baseStats: { hp: 95, attack: 125, defense: 79, specialAttack: 60, specialDefense: 100, speed: 81 },
    learnableMoves: [
      { level: 1, move: MOVES.bite },
      { level: 20, move: MOVES.hydroPump },
    ],
    locations: ['Evolve Magikarp'],
  },
  131: {
    id: 131,
    name: 'Lapras',
    types: ['Water', 'Ice'],
    baseStats: { hp: 130, attack: 85, defense: 80, specialAttack: 85, specialDefense: 95, speed: 60 },
    learnableMoves: [
      { level: 1, move: MOVES.waterGun },
      { level: 16, move: MOVES.iceBeam },
      { level: 25, move: MOVES.surf },
    ],
    locations: ['Silph Co.'],
  },
  132: {
    id: 132,
    name: 'Ditto',
    types: ['Normal'],
    baseStats: { hp: 48, attack: 48, defense: 48, specialAttack: 48, specialDefense: 48, speed: 48 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Route 13', 'Route 14', 'Route 15', 'Route 23', 'Cerulean Cave'],
  },
  133: {
    id: 133,
    name: 'Eevee',
    types: ['Normal'],
    baseStats: { hp: 55, attack: 55, defense: 50, specialAttack: 45, specialDefense: 65, speed: 55 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 16, move: MOVES.quickAttack },
    ],
    locations: ['Celadon City Mansion'],
  },
  134: {
    id: 134,
    name: 'Vaporeon',
    types: ['Water'],
    baseStats: { hp: 130, attack: 65, defense: 60, specialAttack: 110, specialDefense: 95, speed: 65 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 16, move: MOVES.waterGun },
      { level: 27, move: MOVES.surf },
    ],
    locations: ['Evolve Eevee with Water Stone'],
  },
  135: {
    id: 135,
    name: 'Jolteon',
    types: ['Electric'],
    baseStats: { hp: 65, attack: 65, defense: 60, specialAttack: 110, specialDefense: 95, speed: 130 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 16, move: MOVES.thunderShock },
      { level: 27, move: MOVES.thunderbolt },
    ],
    locations: ['Evolve Eevee with Thunder Stone'],
  },
  136: {
    id: 136,
    name: 'Flareon',
    types: ['Fire'],
    baseStats: { hp: 65, attack: 130, defense: 60, specialAttack: 95, specialDefense: 110, speed: 65 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 16, move: MOVES.ember },
      { level: 27, move: MOVES.flamethrower },
    ],
    locations: ['Evolve Eevee with Fire Stone'],
  },
  137: {
    id: 137,
    name: 'Porygon',
    types: ['Normal'],
    baseStats: { hp: 65, attack: 60, defense: 70, specialAttack: 85, specialDefense: 75, speed: 40 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Celadon Game Corner Prize'],
  },
  138: {
    id: 138,
    name: 'Omanyte',
    types: ['Rock', 'Water'],
    baseStats: { hp: 35, attack: 40, defense: 100, specialAttack: 90, specialDefense: 55, speed: 35 },
    learnableMoves: [
      { level: 1, move: MOVES.waterGun },
      { level: 19, move: MOVES.bite },
    ],
    locations: ['Revive from Helix Fossil'],
    evolutionLevel: 40,
    evolutionTarget: 'Omastar',
  },
  139: {
    id: 139,
    name: 'Omastar',
    types: ['Rock', 'Water'],
    baseStats: { hp: 70, attack: 60, defense: 125, specialAttack: 115, specialDefense: 70, speed: 55 },
    learnableMoves: [
      { level: 1, move: MOVES.waterGun },
      { level: 19, move: MOVES.bite },
      { level: 40, move: MOVES.surf },
    ],
    locations: ['Evolve Omanyte'],
  },
  140: {
    id: 140,
    name: 'Kabuto',
    types: ['Rock', 'Water'],
    baseStats: { hp: 30, attack: 80, defense: 90, specialAttack: 55, specialDefense: 45, speed: 55 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 19, move: MOVES.waterGun },
    ],
    locations: ['Revive from Dome Fossil'],
    evolutionLevel: 40,
    evolutionTarget: 'Kabutops',
  },
  141: {
    id: 141,
    name: 'Kabutops',
    types: ['Rock', 'Water'],
    baseStats: { hp: 60, attack: 115, defense: 105, specialAttack: 65, specialDefense: 70, speed: 80 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 19, move: MOVES.waterGun },
    ],
    locations: ['Evolve Kabuto'],
  },
  142: {
    id: 142,
    name: 'Aerodactyl',
    types: ['Rock', 'Flying'],
    baseStats: { hp: 80, attack: 105, defense: 65, specialAttack: 60, specialDefense: 75, speed: 130 },
    learnableMoves: [
      { level: 1, move: MOVES.bite },
      { level: 33, move: MOVES.hyperBeam },
    ],
    locations: ['Revive from Old Amber'],
  },
  143: {
    id: 143,
    name: 'Snorlax',
    types: ['Normal'],
    baseStats: { hp: 160, attack: 110, defense: 65, specialAttack: 65, specialDefense: 110, speed: 30 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 35, move: MOVES.hyperBeam },
    ],
    locations: ['Route 12', 'Route 16'],
  },
  144: {
    id: 144,
    name: 'Articuno',
    types: ['Ice', 'Flying'],
    baseStats: { hp: 90, attack: 85, defense: 100, specialAttack: 95, specialDefense: 125, speed: 85 },
    learnableMoves: [
      { level: 1, move: MOVES.peck },
      { level: 51, move: MOVES.iceBeam },
    ],
    locations: ['Seafoam Islands'],
  },
  145: {
    id: 145,
    name: 'Zapdos',
    types: ['Electric', 'Flying'],
    baseStats: { hp: 90, attack: 90, defense: 85, specialAttack: 125, specialDefense: 90, speed: 100 },
    learnableMoves: [
      { level: 1, move: MOVES.peck },
      { level: 51, move: MOVES.thunderbolt },
    ],
    locations: ['Power Plant'],
  },
  146: {
    id: 146,
    name: 'Moltres',
    types: ['Fire', 'Flying'],
    baseStats: { hp: 90, attack: 100, defense: 90, specialAttack: 125, specialDefense: 85, speed: 90 },
    learnableMoves: [
      { level: 1, move: MOVES.peck },
      { level: 51, move: MOVES.flamethrower },
    ],
    locations: ['Victory Road'],
  },
  147: {
    id: 147,
    name: 'Dratini',
    types: ['Dragon'],
    baseStats: { hp: 41, attack: 64, defense: 45, specialAttack: 50, specialDefense: 50, speed: 50 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Safari Zone'],
    evolutionLevel: 30,
    evolutionTarget: 'Dragonair',
  },
  148: {
    id: 148,
    name: 'Dragonair',
    types: ['Dragon'],
    baseStats: { hp: 61, attack: 84, defense: 65, specialAttack: 70, specialDefense: 70, speed: 70 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
    ],
    locations: ['Safari Zone', 'Evolve Dratini'],
    evolutionLevel: 55,
    evolutionTarget: 'Dragonite',
  },
  149: {
    id: 149,
    name: 'Dragonite',
    types: ['Dragon', 'Flying'],
    baseStats: { hp: 91, attack: 134, defense: 95, specialAttack: 100, specialDefense: 100, speed: 80 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 55, move: MOVES.hyperBeam },
    ],
    locations: ['Evolve Dragonair'],
  },
  150: {
    id: 150,
    name: 'Mewtwo',
    types: ['Psychic'],
    baseStats: { hp: 106, attack: 110, defense: 90, specialAttack: 154, specialDefense: 90, speed: 130 },
    learnableMoves: [
      { level: 1, move: MOVES.confusion },
      { level: 70, move: MOVES.psychic },
    ],
    locations: ['Cerulean Cave'],
  },
  151: {
    id: 151,
    name: 'Mew',
    types: ['Psychic'],
    baseStats: { hp: 100, attack: 100, defense: 100, specialAttack: 100, specialDefense: 100, speed: 100 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 10, move: MOVES.confusion },
      { level: 20, move: MOVES.psychic },
    ],
    locations: ['Special Event'],
  },
};

// Helper function to get Pokemon by ID
export function getPokemonData(id: number): PokedexEntry | undefined {
  return POKEDEX[id];
}

// Helper function to get all Pokemon IDs
export function getAllPokemonIds(): number[] {
  return Object.keys(POKEDEX).map(id => parseInt(id));
}
