import { PokedexEntry, PokemonType, Stats, Move } from '@/types/game';

// Common moves used throughout the game
export const MOVES: { [key: string]: Move } = {
  tackle: { name: 'Tackle', type: 'Normal', power: 40, accuracy: 100, pp: 35, maxPp: 35 },
  scratch: { name: 'Scratch', type: 'Normal', power: 40, accuracy: 100, pp: 35, maxPp: 35 },
  ember: { name: 'Ember', type: 'Fire', power: 40, accuracy: 100, pp: 25, maxPp: 25 },
  waterGun: { name: 'Water Gun', type: 'Water', power: 40, accuracy: 100, pp: 25, maxPp: 25 },
  vineWhip: { name: 'Vine Whip', type: 'Grass', power: 45, accuracy: 100, pp: 25, maxPp: 25 },
  thunderShock: { name: 'Thunder Shock', type: 'Electric', power: 40, accuracy: 100, pp: 30, maxPp: 30 },
  bite: { name: 'Bite', type: 'Dark', power: 60, accuracy: 100, pp: 25, maxPp: 25 },
  flamethrower: { name: 'Flamethrower', type: 'Fire', power: 90, accuracy: 100, pp: 15, maxPp: 15 },
  hydroPump: { name: 'Hydro Pump', type: 'Water', power: 110, accuracy: 80, pp: 5, maxPp: 5 },
  solarBeam: { name: 'Solar Beam', type: 'Grass', power: 120, accuracy: 100, pp: 10, maxPp: 10 },
  thunderbolt: { name: 'Thunderbolt', type: 'Electric', power: 90, accuracy: 100, pp: 15, maxPp: 15 },
  psychic: { name: 'Psychic', type: 'Psychic', power: 90, accuracy: 100, pp: 10, maxPp: 10 },
  earthquake: { name: 'Earthquake', type: 'Ground', power: 100, accuracy: 100, pp: 10, maxPp: 10 },
  iceBeam: { name: 'Ice Beam', type: 'Ice', power: 90, accuracy: 100, pp: 10, maxPp: 10 },
  surf: { name: 'Surf', type: 'Water', power: 90, accuracy: 100, pp: 15, maxPp: 15 },
  hyperBeam: { name: 'Hyper Beam', type: 'Normal', power: 150, accuracy: 90, pp: 5, maxPp: 5 },
  quickAttack: { name: 'Quick Attack', type: 'Normal', power: 40, accuracy: 100, pp: 30, maxPp: 30 },
  confusion: { name: 'Confusion', type: 'Psychic', power: 50, accuracy: 100, pp: 25, maxPp: 25 },
  razorLeaf: { name: 'Razor Leaf', type: 'Grass', power: 55, accuracy: 95, pp: 25, maxPp: 25 },
  bubble: { name: 'Bubble', type: 'Water', power: 40, accuracy: 100, pp: 30, maxPp: 30 },
  peck: { name: 'Peck', type: 'Flying', power: 35, accuracy: 100, pp: 35, maxPp: 35 },
  gust: { name: 'Gust', type: 'Flying', power: 40, accuracy: 100, pp: 35, maxPp: 35 },
  poisonSting: { name: 'Poison Sting', type: 'Poison', power: 15, accuracy: 100, pp: 35, maxPp: 35 },
  rockThrow: { name: 'Rock Throw', type: 'Rock', power: 50, accuracy: 90, pp: 15, maxPp: 15 },
};

// Complete Kanto Pokedex (151 Pokemon)
export const POKEDEX: { [id: number]: PokedexEntry } = {
  1: {
    id: 1,
    name: 'Bulbasaur',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 45, attack: 49, defense: 49, specialAttack: 65, specialDefense: 65, speed: 45 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 7, move: MOVES.vineWhip },
      { level: 13, move: MOVES.razorLeaf },
    ],
    locations: ['Starter Pokemon from Professor Oak'],
    evolutionLevel: 16,
    evolutionTarget: 'Ivysaur',
  },
  2: {
    id: 2,
    name: 'Ivysaur',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 60, attack: 62, defense: 63, specialAttack: 80, specialDefense: 80, speed: 60 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 7, move: MOVES.vineWhip },
      { level: 13, move: MOVES.razorLeaf },
    ],
    locations: ['Evolve Bulbasaur'],
    evolutionLevel: 32,
    evolutionTarget: 'Venusaur',
  },
  3: {
    id: 3,
    name: 'Venusaur',
    types: ['Grass', 'Poison'],
    baseStats: { hp: 80, attack: 82, defense: 83, specialAttack: 100, specialDefense: 100, speed: 80 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 7, move: MOVES.vineWhip },
      { level: 13, move: MOVES.razorLeaf },
      { level: 32, move: MOVES.solarBeam },
    ],
    locations: ['Evolve Ivysaur'],
  },
  4: {
    id: 4,
    name: 'Charmander',
    types: ['Fire'],
    baseStats: { hp: 39, attack: 52, defense: 43, specialAttack: 60, specialDefense: 50, speed: 65 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 7, move: MOVES.ember },
    ],
    locations: ['Starter Pokemon from Professor Oak'],
    evolutionLevel: 16,
    evolutionTarget: 'Charmeleon',
  },
  5: {
    id: 5,
    name: 'Charmeleon',
    types: ['Fire'],
    baseStats: { hp: 58, attack: 64, defense: 58, specialAttack: 80, specialDefense: 65, speed: 80 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 7, move: MOVES.ember },
    ],
    locations: ['Evolve Charmander'],
    evolutionLevel: 36,
    evolutionTarget: 'Charizard',
  },
  6: {
    id: 6,
    name: 'Charizard',
    types: ['Fire', 'Flying'],
    baseStats: { hp: 78, attack: 84, defense: 78, specialAttack: 109, specialDefense: 85, speed: 100 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 7, move: MOVES.ember },
      { level: 36, move: MOVES.flamethrower },
    ],
    locations: ['Evolve Charmeleon'],
  },
  7: {
    id: 7,
    name: 'Squirtle',
    types: ['Water'],
    baseStats: { hp: 44, attack: 48, defense: 65, specialAttack: 50, specialDefense: 64, speed: 43 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 7, move: MOVES.bubble },
      { level: 10, move: MOVES.waterGun },
    ],
    locations: ['Starter Pokemon from Professor Oak'],
    evolutionLevel: 16,
    evolutionTarget: 'Wartortle',
  },
  8: {
    id: 8,
    name: 'Wartortle',
    types: ['Water'],
    baseStats: { hp: 59, attack: 63, defense: 80, specialAttack: 65, specialDefense: 80, speed: 58 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 7, move: MOVES.bubble },
      { level: 10, move: MOVES.waterGun },
    ],
    locations: ['Evolve Squirtle'],
    evolutionLevel: 36,
    evolutionTarget: 'Blastoise',
  },
  9: {
    id: 9,
    name: 'Blastoise',
    types: ['Water'],
    baseStats: { hp: 79, attack: 83, defense: 100, specialAttack: 85, specialDefense: 105, speed: 78 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 7, move: MOVES.bubble },
      { level: 10, move: MOVES.waterGun },
      { level: 36, move: MOVES.hydroPump },
    ],
    locations: ['Evolve Wartortle'],
  },
  10: {
    id: 10,
    name: 'Caterpie',
    types: ['Bug'],
    baseStats: { hp: 45, attack: 30, defense: 35, specialAttack: 20, specialDefense: 20, speed: 45 },
    learnableMoves: [{ level: 1, move: MOVES.tackle }],
    locations: ['Route 2', 'Route 24', 'Route 25', 'Viridian Forest'],
    evolutionLevel: 7,
    evolutionTarget: 'Metapod',
  },
  11: {
    id: 11,
    name: 'Metapod',
    types: ['Bug'],
    baseStats: { hp: 50, attack: 20, defense: 55, specialAttack: 25, specialDefense: 25, speed: 30 },
    learnableMoves: [{ level: 1, move: MOVES.tackle }],
    locations: ['Route 24', 'Route 25', 'Viridian Forest', 'Evolve Caterpie'],
    evolutionLevel: 10,
    evolutionTarget: 'Butterfree',
  },
  12: {
    id: 12,
    name: 'Butterfree',
    types: ['Bug', 'Flying'],
    baseStats: { hp: 60, attack: 45, defense: 50, specialAttack: 90, specialDefense: 80, speed: 70 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 10, move: MOVES.confusion },
    ],
    locations: ['Evolve Metapod'],
  },
  13: {
    id: 13,
    name: 'Weedle',
    types: ['Bug', 'Poison'],
    baseStats: { hp: 40, attack: 35, defense: 30, specialAttack: 20, specialDefense: 20, speed: 50 },
    learnableMoves: [{ level: 1, move: MOVES.poisonSting }],
    locations: ['Route 2', 'Route 24', 'Route 25', 'Viridian Forest'],
    evolutionLevel: 7,
    evolutionTarget: 'Kakuna',
  },
  14: {
    id: 14,
    name: 'Kakuna',
    types: ['Bug', 'Poison'],
    baseStats: { hp: 45, attack: 25, defense: 50, specialAttack: 25, specialDefense: 25, speed: 35 },
    learnableMoves: [{ level: 1, move: MOVES.poisonSting }],
    locations: ['Route 24', 'Route 25', 'Viridian Forest', 'Evolve Weedle'],
    evolutionLevel: 10,
    evolutionTarget: 'Beedrill',
  },
  15: {
    id: 15,
    name: 'Beedrill',
    types: ['Bug', 'Poison'],
    baseStats: { hp: 65, attack: 90, defense: 40, specialAttack: 45, specialDefense: 80, speed: 75 },
    learnableMoves: [
      { level: 1, move: MOVES.poisonSting },
      { level: 10, move: MOVES.quickAttack },
    ],
    locations: ['Evolve Kakuna'],
  },
  16: {
    id: 16,
    name: 'Pidgey',
    types: ['Normal', 'Flying'],
    baseStats: { hp: 40, attack: 45, defense: 40, specialAttack: 35, specialDefense: 35, speed: 56 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 5, move: MOVES.gust },
    ],
    locations: ['Route 1', 'Route 2', 'Route 3', 'Route 5', 'Route 6', 'Route 7', 'Route 8', 'Route 12', 'Route 13', 'Route 14', 'Route 15'],
    evolutionLevel: 18,
    evolutionTarget: 'Pidgeotto',
  },
  17: {
    id: 17,
    name: 'Pidgeotto',
    types: ['Normal', 'Flying'],
    baseStats: { hp: 63, attack: 60, defense: 55, specialAttack: 50, specialDefense: 50, speed: 71 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 5, move: MOVES.gust },
    ],
    locations: ['Route 14', 'Route 15', 'Evolve Pidgey'],
    evolutionLevel: 36,
    evolutionTarget: 'Pidgeot',
  },
  18: {
    id: 18,
    name: 'Pidgeot',
    types: ['Normal', 'Flying'],
    baseStats: { hp: 83, attack: 80, defense: 75, specialAttack: 70, specialDefense: 70, speed: 101 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 5, move: MOVES.gust },
      { level: 36, move: MOVES.quickAttack },
    ],
    locations: ['Evolve Pidgeotto'],
  },
  19: {
    id: 19,
    name: 'Rattata',
    types: ['Normal'],
    baseStats: { hp: 30, attack: 56, defense: 35, specialAttack: 25, specialDefense: 35, speed: 72 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 7, move: MOVES.quickAttack },
      { level: 14, move: MOVES.bite },
    ],
    locations: ['Route 1', 'Route 2', 'Route 3', 'Route 4', 'Route 9', 'Route 10', 'Route 11', 'Route 16', 'Route 17', 'Route 18', 'Pokemon Mansion'],
    evolutionLevel: 20,
    evolutionTarget: 'Raticate',
  },
  20: {
    id: 20,
    name: 'Raticate',
    types: ['Normal'],
    baseStats: { hp: 55, attack: 81, defense: 60, specialAttack: 50, specialDefense: 70, speed: 97 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 7, move: MOVES.quickAttack },
      { level: 14, move: MOVES.bite },
    ],
    locations: ['Route 9', 'Route 10', 'Route 11', 'Route 16', 'Route 17', 'Route 18', 'Pokemon Mansion', 'Evolve Rattata'],
  },
  25: {
    id: 25,
    name: 'Pikachu',
    types: ['Electric'],
    baseStats: { hp: 35, attack: 55, defense: 40, specialAttack: 50, specialDefense: 50, speed: 90 },
    learnableMoves: [
      { level: 1, move: MOVES.thunderShock },
      { level: 8, move: MOVES.quickAttack },
      { level: 26, move: MOVES.thunderbolt },
    ],
    locations: ['Viridian Forest', 'Power Plant'],
    evolutionLevel: 26,
    evolutionTarget: 'Raichu',
  },
  26: {
    id: 26,
    name: 'Raichu',
    types: ['Electric'],
    baseStats: { hp: 60, attack: 90, defense: 55, specialAttack: 90, specialDefense: 80, speed: 110 },
    learnableMoves: [
      { level: 1, move: MOVES.thunderShock },
      { level: 26, move: MOVES.thunderbolt },
    ],
    locations: ['Evolve Pikachu'],
  },
  50: {
    id: 50,
    name: 'Diglett',
    types: ['Ground'],
    baseStats: { hp: 10, attack: 55, defense: 25, specialAttack: 35, specialDefense: 45, speed: 95 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 15, move: MOVES.earthquake },
    ],
    locations: ['Digletts Cave'],
    evolutionLevel: 26,
    evolutionTarget: 'Dugtrio',
  },
  51: {
    id: 51,
    name: 'Dugtrio',
    types: ['Ground'],
    baseStats: { hp: 35, attack: 100, defense: 50, specialAttack: 50, specialDefense: 70, speed: 120 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 15, move: MOVES.earthquake },
    ],
    locations: ['Digletts Cave', 'Evolve Diglett'],
  },
  54: {
    id: 54,
    name: 'Psyduck',
    types: ['Water'],
    baseStats: { hp: 50, attack: 52, defense: 48, specialAttack: 65, specialDefense: 50, speed: 55 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 10, move: MOVES.waterGun },
      { level: 28, move: MOVES.confusion },
    ],
    locations: ['Route 4', 'Route 6', 'Route 11', 'Route 13', 'Route 17', 'Route 18', 'Route 22', 'Route 23', 'Cerulean Cave'],
    evolutionLevel: 33,
    evolutionTarget: 'Golduck',
  },
  55: {
    id: 55,
    name: 'Golduck',
    types: ['Water'],
    baseStats: { hp: 80, attack: 82, defense: 78, specialAttack: 95, specialDefense: 80, speed: 85 },
    learnableMoves: [
      { level: 1, move: MOVES.scratch },
      { level: 10, move: MOVES.waterGun },
      { level: 28, move: MOVES.confusion },
      { level: 33, move: MOVES.psychic },
    ],
    locations: ['Route 6', 'Route 22', 'Route 23', 'Cerulean Cave', 'Evolve Psyduck'],
  },
  74: {
    id: 74,
    name: 'Geodude',
    types: ['Rock', 'Ground'],
    baseStats: { hp: 40, attack: 80, defense: 100, specialAttack: 30, specialDefense: 30, speed: 20 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 11, move: MOVES.rockThrow },
    ],
    locations: ['Mt. Moon', 'Rock Tunnel', 'Victory Road'],
    evolutionLevel: 25,
    evolutionTarget: 'Graveler',
  },
  75: {
    id: 75,
    name: 'Graveler',
    types: ['Rock', 'Ground'],
    baseStats: { hp: 55, attack: 95, defense: 115, specialAttack: 45, specialDefense: 45, speed: 35 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 11, move: MOVES.rockThrow },
      { level: 25, move: MOVES.earthquake },
    ],
    locations: ['Rock Tunnel', 'Victory Road', 'Cerulean Cave', 'Evolve Geodude'],
    evolutionLevel: 40,
    evolutionTarget: 'Golem',
  },
  76: {
    id: 76,
    name: 'Golem',
    types: ['Rock', 'Ground'],
    baseStats: { hp: 80, attack: 120, defense: 130, specialAttack: 55, specialDefense: 65, speed: 45 },
    learnableMoves: [
      { level: 1, move: MOVES.tackle },
      { level: 11, move: MOVES.rockThrow },
      { level: 25, move: MOVES.earthquake },
    ],
    locations: ['Evolve Graveler'],
  },
  129: {
    id: 129,
    name: 'Magikarp',
    types: ['Water'],
    baseStats: { hp: 20, attack: 10, defense: 55, specialAttack: 15, specialDefense: 20, speed: 80 },
    learnableMoves: [{ level: 1, move: MOVES.tackle }],
    locations: ['Any fishing spot'],
    evolutionLevel: 20,
    evolutionTarget: 'Gyarados',
  },
  130: {
    id: 130,
    name: 'Gyarados',
    types: ['Water', 'Flying'],
    baseStats: { hp: 95, attack: 125, defense: 79, specialAttack: 60, specialDefense: 100, speed: 81 },
    learnableMoves: [
      { level: 1, move: MOVES.bite },
      { level: 20, move: MOVES.hydroPump },
    ],
    locations: ['Evolve Magikarp'],
  },
  150: {
    id: 150,
    name: 'Mewtwo',
    types: ['Psychic'],
    baseStats: { hp: 106, attack: 110, defense: 90, specialAttack: 154, specialDefense: 90, speed: 130 },
    learnableMoves: [
      { level: 1, move: MOVES.confusion },
      { level: 70, move: MOVES.psychic },
    ],
    locations: ['Cerulean Cave'],
  },
};

// Helper function to get Pokemon by ID
export function getPokemonData(id: number): PokedexEntry | undefined {
  return POKEDEX[id];
}

// Helper function to get all Pokemon IDs
export function getAllPokemonIds(): number[] {
  return Object.keys(POKEDEX).map(id => parseInt(id));
}
